name: Tests
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
    tox:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python_version:
            - "3.8"
          tox_env:
            - py
          include:
            - tox_env: py
              friendly_name: Tests
        fail-fast: false
      name: Tox - ${{ matrix.friendly_name }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ env.ref }}
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python_version }}
        - name: Install tox
          run: |
            python -m pip install --upgrade pip
            pip install tox
        - name: Register problem matcher
          run: |
            echo "::add-matcher::.github/workflows/matchers/sphinx.json"
        - name: Tox test
          env:
            TOXENV: ${{ matrix.tox_env }}
          run: tox
